// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

type Alignment = byte
const (
	AlignmentStart Alignment = 0
	AlignmentEnd Alignment = 1
	AlignmentMiddle Alignment = 2
	AlignmentBaseline Alignment = 3
)

var EnumNamesAlignment = map[Alignment]string{
	AlignmentStart:"Start",
	AlignmentEnd:"End",
	AlignmentMiddle:"Middle",
	AlignmentBaseline:"Baseline",
}

