// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Constraint struct {
	_tab flatbuffers.Struct
}

func (rcv *Constraint) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Constraint) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Constraint) Min() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Constraint) MutateMin(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Constraint) Max() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Constraint) MutateMax(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateConstraint(builder *flatbuffers.Builder, min int32, max int32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependInt32(max)
	builder.PrependInt32(min)
	return builder.Offset()
}
