// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Face struct {
	_tab flatbuffers.Table
}

func GetRootAsFace(buf []byte, offset flatbuffers.UOffsetT) *Face {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Face{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Face) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Face) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Face) Font() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Face) Size(obj *Value) *Value {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Value)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func FaceStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FaceAddFont(builder *flatbuffers.Builder, font flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(font), 0)
}
func FaceAddSize(builder *flatbuffers.Builder, size flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(size), 0)
}
func FaceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
