// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type Image byte

const (
	ImageNONE        Image = 0
	ImageImageDecode Image = 1
	ImageImageNRGBA  Image = 2
)

var EnumNamesImage = map[Image]string{
	ImageNONE:        "NONE",
	ImageImageDecode: "ImageDecode",
	ImageImageNRGBA:  "ImageNRGBA",
}

var EnumValuesImage = map[string]Image{
	"NONE":        ImageNONE,
	"ImageDecode": ImageImageDecode,
	"ImageNRGBA":  ImageImageNRGBA,
}

func (v Image) String() string {
	if s, ok := EnumNamesImage[v]; ok {
		return s
	}
	return "Image(" + strconv.FormatInt(int64(v), 10) + ")"
}
