// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type LayoutAxis byte

const (
	LayoutAxisHorizontal LayoutAxis = 0
	LayoutAxisVertical   LayoutAxis = 1
)

var EnumNamesLayoutAxis = map[LayoutAxis]string{
	LayoutAxisHorizontal: "Horizontal",
	LayoutAxisVertical:   "Vertical",
}

var EnumValuesLayoutAxis = map[string]LayoutAxis{
	"Horizontal": LayoutAxisHorizontal,
	"Vertical":   LayoutAxisVertical,
}

func (v LayoutAxis) String() string {
	if s, ok := EnumNamesLayoutAxis[v]; ok {
		return s
	}
	return "LayoutAxis(" + strconv.FormatInt(int64(v), 10) + ")"
}
