// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type LayoutFlexChild byte

const (
	LayoutFlexChildNONE   LayoutFlexChild = 0
	LayoutFlexChildFlexed LayoutFlexChild = 1
	LayoutFlexChildRigid  LayoutFlexChild = 2
)

var EnumNamesLayoutFlexChild = map[LayoutFlexChild]string{
	LayoutFlexChildNONE:   "NONE",
	LayoutFlexChildFlexed: "Flexed",
	LayoutFlexChildRigid:  "Rigid",
}

var EnumValuesLayoutFlexChild = map[string]LayoutFlexChild{
	"NONE":   LayoutFlexChildNONE,
	"Flexed": LayoutFlexChildFlexed,
	"Rigid":  LayoutFlexChildRigid,
}

func (v LayoutFlexChild) String() string {
	if s, ok := EnumNamesLayoutFlexChild[v]; ok {
		return s
	}
	return "LayoutFlexChild(" + strconv.FormatInt(int64(v), 10) + ")"
}
