// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LayoutSpacer struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutSpacer(buf []byte, offset flatbuffers.UOffsetT) *LayoutSpacer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutSpacer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LayoutSpacer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutSpacer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutSpacer) Width(obj *UnitValue) *UnitValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(UnitValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *LayoutSpacer) Height(obj *UnitValue) *UnitValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(UnitValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LayoutSpacerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LayoutSpacerAddWidth(builder *flatbuffers.Builder, width flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(width), 0)
}
func LayoutSpacerAddHeight(builder *flatbuffers.Builder, height flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(height), 0)
}
func LayoutSpacerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
