// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LayoutDirectionLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutDirectionLayout(buf []byte, offset flatbuffers.UOffsetT) *LayoutDirectionLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutDirectionLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LayoutDirectionLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutDirectionLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutDirectionLayout) Direction() LayoutDirection {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return LayoutDirection(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LayoutDirectionLayout) MutateDirection(n LayoutDirection) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *LayoutDirectionLayout) Widget(obj *OpNode) *OpNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OpNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LayoutDirectionLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LayoutDirectionLayoutAddDirection(builder *flatbuffers.Builder, direction LayoutDirection) {
	builder.PrependByteSlot(0, byte(direction), 0)
}
func LayoutDirectionLayoutAddWidget(builder *flatbuffers.Builder, widget flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(widget), 0)
}
func LayoutDirectionLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
