// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type LayoutDirection byte

const (
	LayoutDirectionNW     LayoutDirection = 0
	LayoutDirectionN      LayoutDirection = 1
	LayoutDirectionNE     LayoutDirection = 2
	LayoutDirectionE      LayoutDirection = 3
	LayoutDirectionSE     LayoutDirection = 4
	LayoutDirectionS      LayoutDirection = 5
	LayoutDirectionSW     LayoutDirection = 6
	LayoutDirectionW      LayoutDirection = 7
	LayoutDirectionCenter LayoutDirection = 8
)

var EnumNamesLayoutDirection = map[LayoutDirection]string{
	LayoutDirectionNW:     "NW",
	LayoutDirectionN:      "N",
	LayoutDirectionNE:     "NE",
	LayoutDirectionE:      "E",
	LayoutDirectionSE:     "SE",
	LayoutDirectionS:      "S",
	LayoutDirectionSW:     "SW",
	LayoutDirectionW:      "W",
	LayoutDirectionCenter: "Center",
}

var EnumValuesLayoutDirection = map[string]LayoutDirection{
	"NW":     LayoutDirectionNW,
	"N":      LayoutDirectionN,
	"NE":     LayoutDirectionNE,
	"E":      LayoutDirectionE,
	"SE":     LayoutDirectionSE,
	"S":      LayoutDirectionS,
	"SW":     LayoutDirectionSW,
	"W":      LayoutDirectionW,
	"Center": LayoutDirectionCenter,
}

func (v LayoutDirection) String() string {
	if s, ok := EnumNamesLayoutDirection[v]; ok {
		return s
	}
	return "LayoutDirection(" + strconv.FormatInt(int64(v), 10) + ")"
}
