// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LayoutSpacerLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutSpacerLayout(buf []byte, offset flatbuffers.UOffsetT) *LayoutSpacerLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutSpacerLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LayoutSpacerLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutSpacerLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutSpacerLayout) Spacer(obj *LayoutSpacer) *LayoutSpacer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LayoutSpacer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LayoutSpacerLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LayoutSpacerLayoutAddSpacer(builder *flatbuffers.Builder, spacer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(spacer), 0)
}
func LayoutSpacerLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
