// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LayoutStack struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutStack(buf []byte, offset flatbuffers.UOffsetT) *LayoutStack {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutStack{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LayoutStack) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutStack) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutStack) Alignment() LayoutDirection {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return LayoutDirection(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LayoutStack) MutateAlignment(n LayoutDirection) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func LayoutStackStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LayoutStackAddAlignment(builder *flatbuffers.Builder, alignment LayoutDirection) {
	builder.PrependByteSlot(0, byte(alignment), 0)
}
func LayoutStackEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
