// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type LayoutSpacing byte

const (
	LayoutSpacingEnd     LayoutSpacing = 0
	LayoutSpacingStart   LayoutSpacing = 1
	LayoutSpacingSides   LayoutSpacing = 2
	LayoutSpacingAround  LayoutSpacing = 3
	LayoutSpacingBetween LayoutSpacing = 4
	LayoutSpacingEvenly  LayoutSpacing = 5
)

var EnumNamesLayoutSpacing = map[LayoutSpacing]string{
	LayoutSpacingEnd:     "End",
	LayoutSpacingStart:   "Start",
	LayoutSpacingSides:   "Sides",
	LayoutSpacingAround:  "Around",
	LayoutSpacingBetween: "Between",
	LayoutSpacingEvenly:  "Evenly",
}

var EnumValuesLayoutSpacing = map[string]LayoutSpacing{
	"End":     LayoutSpacingEnd,
	"Start":   LayoutSpacingStart,
	"Sides":   LayoutSpacingSides,
	"Around":  LayoutSpacingAround,
	"Between": LayoutSpacingBetween,
	"Evenly":  LayoutSpacingEvenly,
}

func (v LayoutSpacing) String() string {
	if s, ok := EnumNamesLayoutSpacing[v]; ok {
		return s
	}
	return "LayoutSpacing(" + strconv.FormatInt(int64(v), 10) + ")"
}
