// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LayoutInsetLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutInsetLayout(buf []byte, offset flatbuffers.UOffsetT) *LayoutInsetLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutInsetLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LayoutInsetLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutInsetLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutInsetLayout) Inset(obj *LayoutInset) *LayoutInset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LayoutInset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *LayoutInsetLayout) Widget(obj *OpNode) *OpNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OpNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LayoutInsetLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LayoutInsetLayoutAddInset(builder *flatbuffers.Builder, inset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(inset), 0)
}
func LayoutInsetLayoutAddWidget(builder *flatbuffers.Builder, widget flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(widget), 0)
}
func LayoutInsetLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
