// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LayoutFlexLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsLayoutFlexLayout(buf []byte, offset flatbuffers.UOffsetT) *LayoutFlexLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LayoutFlexLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LayoutFlexLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LayoutFlexLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LayoutFlexLayout) Flex(obj *LayoutFlex) *LayoutFlex {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LayoutFlex)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *LayoutFlexLayout) Children(obj *LayoutFlexChildNode) *LayoutFlexChildNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LayoutFlexChildNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LayoutFlexLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LayoutFlexLayoutAddFlex(builder *flatbuffers.Builder, flex flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(flex), 0)
}
func LayoutFlexLayoutAddChildren(builder *flatbuffers.Builder, children flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(children), 0)
}
func LayoutFlexLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
