// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type Op byte

const (
	OpNONE                Op = 0
	OpMacro               Op = 1
	OpPaintColor          Op = 2
	OpPaintLinearGradient Op = 3
	OpPaint               Op = 4
	OpWidgetLabel         Op = 5
)

var EnumNamesOp = map[Op]string{
	OpNONE:                "NONE",
	OpMacro:               "Macro",
	OpPaintColor:          "PaintColor",
	OpPaintLinearGradient: "PaintLinearGradient",
	OpPaint:               "Paint",
	OpWidgetLabel:         "WidgetLabel",
}

var EnumValuesOp = map[string]Op{
	"NONE":                OpNONE,
	"Macro":               OpMacro,
	"PaintColor":          OpPaintColor,
	"PaintLinearGradient": OpPaintLinearGradient,
	"Paint":               OpPaint,
	"WidgetLabel":         OpWidgetLabel,
}

func (v Op) String() string {
	if s, ok := EnumNamesOp[v]; ok {
		return s
	}
	return "Op(" + strconv.FormatInt(int64(v), 10) + ")"
}
