// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaintColorOp struct {
	_tab flatbuffers.Table
}

func GetRootAsPaintColorOp(buf []byte, offset flatbuffers.UOffsetT) *PaintColorOp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaintColorOp{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PaintColorOp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaintColorOp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PaintColorOp) Color(obj *ColorNRGBA) *ColorNRGBA {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(ColorNRGBA)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PaintColorOpStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PaintColorOpAddColor(builder *flatbuffers.Builder, color flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(color), 0)
}
func PaintColorOpEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
