// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaintOp struct {
	_tab flatbuffers.Table
}

func GetRootAsPaintOp(buf []byte, offset flatbuffers.UOffsetT) *PaintOp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaintOp{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PaintOp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaintOp) Table() flatbuffers.Table {
	return rcv._tab
}

func PaintOpStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PaintOpEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
