// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type TextAlignment byte

const (
	TextAlignmentStart  TextAlignment = 0
	TextAlignmentEnd    TextAlignment = 1
	TextAlignmentMiddle TextAlignment = 2
)

var EnumNamesTextAlignment = map[TextAlignment]string{
	TextAlignmentStart:  "Start",
	TextAlignmentEnd:    "End",
	TextAlignmentMiddle: "Middle",
}

var EnumValuesTextAlignment = map[string]TextAlignment{
	"Start":  TextAlignmentStart,
	"End":    TextAlignmentEnd,
	"Middle": TextAlignmentMiddle,
}

func (v TextAlignment) String() string {
	if s, ok := EnumNamesTextAlignment[v]; ok {
		return s
	}
	return "TextAlignment(" + strconv.FormatInt(int64(v), 10) + ")"
}
