// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type TextStyle int32

const (
	TextStyleRegular TextStyle = 0
	TextStyleItalic  TextStyle = 1
)

var EnumNamesTextStyle = map[TextStyle]string{
	TextStyleRegular: "Regular",
	TextStyleItalic:  "Italic",
}

var EnumValuesTextStyle = map[string]TextStyle{
	"Regular": TextStyleRegular,
	"Italic":  TextStyleItalic,
}

func (v TextStyle) String() string {
	if s, ok := EnumNamesTextStyle[v]; ok {
		return s
	}
	return "TextStyle(" + strconv.FormatInt(int64(v), 10) + ")"
}
