// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnitValue struct {
	_tab flatbuffers.Struct
}

func (rcv *UnitValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnitValue) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *UnitValue) V() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *UnitValue) MutateV(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *UnitValue) U() Unit {
	return Unit(rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(4)))
}
func (rcv *UnitValue) MutateU(n Unit) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(4), byte(n))
}

func CreateUnitValue(builder *flatbuffers.Builder, v float32, u Unit) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.Pad(3)
	builder.PrependByte(byte(u))
	builder.PrependFloat32(v)
	return builder.Offset()
}
