// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

type Unit = byte
const (
	UnitPx Unit = 0
	UnitDp Unit = 1
	UnitSp Unit = 2
)

var EnumNamesUnit = map[Unit]string{
	UnitPx:"Px",
	UnitDp:"Dp",
	UnitSp:"Sp",
}

