// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import "strconv"

type Unit byte

const (
	UnitPx Unit = 0
	UnitDp Unit = 1
	UnitSp Unit = 2
)

var EnumNamesUnit = map[Unit]string{
	UnitPx: "Px",
	UnitDp: "Dp",
	UnitSp: "Sp",
}

var EnumValuesUnit = map[string]Unit{
	"Px": UnitPx,
	"Dp": UnitDp,
	"Sp": UnitSp,
}

func (v Unit) String() string {
	if s, ok := EnumNamesUnit[v]; ok {
		return s
	}
	return "Unit(" + strconv.FormatInt(int64(v), 10) + ")"
}
