// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WidgetIconLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsWidgetIconLayout(buf []byte, offset flatbuffers.UOffsetT) *WidgetIconLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WidgetIconLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WidgetIconLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WidgetIconLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WidgetIconLayout) IconId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WidgetIconLayout) Icon(obj *WidgetIcon) *WidgetIcon {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(WidgetIcon)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WidgetIconLayout) Color(obj *ColorNRGBA) *ColorNRGBA {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(ColorNRGBA)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func WidgetIconLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func WidgetIconLayoutAddIconId(builder *flatbuffers.Builder, iconId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(iconId), 0)
}
func WidgetIconLayoutAddIcon(builder *flatbuffers.Builder, icon flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(icon), 0)
}
func WidgetIconLayoutAddColor(builder *flatbuffers.Builder, color flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(color), 0)
}
func WidgetIconLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
