// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WidgetBorder struct {
	_tab flatbuffers.Table
}

func GetRootAsWidgetBorder(buf []byte, offset flatbuffers.UOffsetT) *WidgetBorder {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WidgetBorder{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WidgetBorder) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WidgetBorder) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WidgetBorder) Color(obj *ColorNRGBA) *ColorNRGBA {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(ColorNRGBA)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WidgetBorder) CornerRadius(obj *UnitValue) *UnitValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(UnitValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WidgetBorder) Width(obj *UnitValue) *UnitValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(UnitValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func WidgetBorderStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func WidgetBorderAddColor(builder *flatbuffers.Builder, color flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(color), 0)
}
func WidgetBorderAddCornerRadius(builder *flatbuffers.Builder, cornerRadius flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(cornerRadius), 0)
}
func WidgetBorderAddWidth(builder *flatbuffers.Builder, width flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(width), 0)
}
func WidgetBorderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
