// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WidgetImageLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsWidgetImageLayout(buf []byte, offset flatbuffers.UOffsetT) *WidgetImageLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WidgetImageLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WidgetImageLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WidgetImageLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WidgetImageLayout) Image(obj *WidgetImage) *WidgetImage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(WidgetImage)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func WidgetImageLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WidgetImageLayoutAddImage(builder *flatbuffers.Builder, image flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(image), 0)
}
func WidgetImageLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
