// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WidgetBorderLayout struct {
	_tab flatbuffers.Table
}

func GetRootAsWidgetBorderLayout(buf []byte, offset flatbuffers.UOffsetT) *WidgetBorderLayout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WidgetBorderLayout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WidgetBorderLayout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WidgetBorderLayout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WidgetBorderLayout) Border(obj *WidgetBorder) *WidgetBorder {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(WidgetBorder)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WidgetBorderLayout) Widget(obj *OpNode) *OpNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OpNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func WidgetBorderLayoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func WidgetBorderLayoutAddBorder(builder *flatbuffers.Builder, border flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(border), 0)
}
func WidgetBorderLayoutAddWidget(builder *flatbuffers.Builder, widget flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(widget), 0)
}
func WidgetBorderLayoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
